version: '3.8'

services:
  # The PostgreSQL Database
  db:
    image: postgres:14-alpine
    container_name: order_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=orders
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d orders"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: order_cache
    ports:
      - "6379:6379"

  wiremock:
    image: wiremock/wiremock:latest
    container_name: wiremock_server
    ports:
      - "9090:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings

  # Our Order Enricher Application
  app:
    container_name: order_enricher_app
    build: . # Build from the Dockerfile in the current directory
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      wiremock:
        condition: service_started
    environment:
      - DB_URL=jdbc:postgresql://db:5432/orders
      - DB_USER=user
      - DB_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CUSTOMER_SERVICE_URL=http://wiremock:8080
      - PRODUCT_SERVICE_URL=http://wiremock:8080

volumes:
  postgres_data: