server:
  port: 8080

spring:
  application:
    name: order-enricher
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/orders}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cache:
    type: redis
    redis:
      time-to-live: 10m

# actuator config
  management:
    endpoints:
      web:
        exposure:
          include: health

# Base paths for the generated controller and API docs
openapi:
  orderEnricherAPI:
    base-path: /v1

# URLs for simulated external services
clients:
  customer-service:
    url: ${CUSTOMER_SERVICE_URL:http://localhost:9090}
  product-service:
    url: ${PRODUCT_SERVICE_URL:http://localhost:9090}